name: Deploy to Dokku (pr)

on:
  pull_request:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
            fetch-depth: 0
      - id: extract_branch
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        
      - id: deploy
        name: Deploy to dokku
        uses: ochaplashkin/dokku-deploy-github-action@master
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
            dokku-host: ${{ secrets.DOKKU_HOST }}
            app-name: smoke-test1
            remote-branch: $GITHUB_REF_NAME
            git-push-flags: '--force'