name: Deploy to Dokku (pr)

on:
  pull_request:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
            fetch-depth: 0
      - id: get branch
      - name: Set env
        run: echo "GITHUB_SHA_SHORT=$(echo git branch --show-current)" >> $GITHUB_ENV
      - name: Test
        run: echo $GITHUB_SHA_SHORT
      - id: deploy
        name: Deploy to dokku
        uses: ochaplashkin/dokku-deploy-github-action@master
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
            dokku-host: ${{ secrets.DOKKU_HOST }}
            app-name: smoke-test-${{ github.ref_name }}
            git-push-flags: '--force'